pid nginx.pid;
error_log stderr;
worker_processes 1;
events { worker_connections 64; }
http {
    access_log off;
    client_body_temp_path body;
    proxy_temp_path proxy;
    server {
        listen 10.0.1.10:80;
        location / {
            proxy_pass http://10.0.2.10:8080;
            proxy_connect_timeout 2s;
            proxy_read_timeout 5s;
            proxy_set_header Host $host;
        }
    }
}
